### ISSUE TITLE
Local Contact Definitions 5.3.2 vs 7.5.2

### ISSUE THREAD

**Issue by economidis-nick** [economidis-nick/createXSDforxMCF#27] opened 2019-05-07 00:28 UTC
section 5.3.2.5 mentions that all connection_0d, _1d and _2d should have a `<contact_list>`
![image](https://user-images.githubusercontent.com/33229181/57262940-25da6680-7077-11e9-914c-516d73da8270.png)

* There are no examples for the local contact definition
   * Table 33 (nested elements of connection_0d) has `<contact_list>` -- but no example
   * Table 76 (nested elements of connection_1d) has `<contact_list>` -- but no example
   * Table 136 (nested elements of connection_2d) does not have `<contact_list>`

* Section 5.3.2 defines **global contact** under `<connection_group>` and **local contact** under `<connection_xd>`
* Section 7.5.2 has a competing local contact definition, defined under '<threaded_connection>` only.
  It appears that this has been written to take care of contacts between **thread**, **nut**, **head** and **washers**.
  But it also handles the connected parts, using a different definition 👎 

 
@DrCaFr , I think local contacts should only be handled by the 5.3.2 definition (global & local contacts).
Thread contact (7.5.2) should only be used to define thread friction.
How should we go about this?

@mkalaitz , 
* create examples containing local contact definitions. (done)
* add `<contact_list>` under `<connection_2d>` and update .xsd accordingly.  (done)

@DrCaFr , we cannot fill the document with examples. Should we add references to the examples folder in GitHub ?

**Comment by economidis-nick** [comment] 2019-05-09 14:50
# Two ways to express contacts:

We have 
* **the standard way**, both for **global contacts** and for **local contacts** (5.3.2 Contacts and Friction)
   ![image](https://user-images.githubusercontent.com/33229181/57459533-18da9480-727c-11e9-8c2e-387b88747854.png)

* **another way**, for expressing **local contact around a screw/bolt** (7.5.2 Contacts and Friction).
   The latter one is quite different from the previous
```xml
<contact_list>
	<contact thread=”true” static_friction=”0.8” />   <!-- Friction within thread -->
	<contact index=”1” static_friction=”0.8” />       <!-- Friction between part 1 and next part, 2 -->
	<contact index=”2” static_friction=”0.8” />       <!-- Friction between part 2 and next part, 5 -->
	<contact index=”5” static_friction=”0.8” />       <!-- Friction between part 5 and next part, 6 -->
</contact_list>
```
 
# Contact definition of 7.5.2 is **redundant** and adds **unnecessary complexity**

In xMCF v3.0 we created a definition of `<contact_list>`, especially for `<thread_connections>`.

Example A of section 7.5.2 uses a special `<threaded_connection/contact_list>` definition, to cater for 
friction between thread & nut, as well as contact between flange partners.
The definition is somehow complex (comments show the intended use):

```xml
<connection_0d>
  <loc> 84 60 10 </loc>
  <threaded_connection length="50" static_friction=”0.8” >                    <!-- head-to-washer -->
     <normal_direction x="0" y="0" z="-10"/>
     <washer outer_diameter=”20” attached=”false” static_friction=”0.8” />    <!-- washer-to-1stPart -->
     <bolt>
        <nut diameter="16." static_friction=”0.8”>                              <!-- nut-to-washer -->
          <washer outer_diameter=”25” attached=”false” static_friction=”0.8” /> <!-- nut_washer-to-lastPart -->
        </nut>
     </bolt>
     <!-- LOCAL CONTACT DEFINITION in threaded_connection -->
     <contact_list>
		<contact thread=”true” static_friction=”0.8” />   <!-- Friction within -->
		<contact index=”1” static_friction=”0.8” />       <!-- part 1 to next part, 2 -->
		<contact index=”2” static_friction=”0.8” />       <!-- part 2 to next part, 5 -->
		<contact index=”5” static_friction=”0.8” />       <!-- part 5 to next part, 6 -->
     </contact_list>
  </threaded_connection>
</connection_0d>
````
The only advantage of this definition, is that 
* we can define the **friction on thread**.

Otherwise, 
* it is cryptic:
`<contact index=”1”>` next part is implied
* it is fragile: 
if order of connected parts change, the wrong friction will be assigned!

# Standard contact definition of 5.3.2 is more robust

We can achieve the same contact if, instead, we use the **standard contact definition** for the friction between parts, and the 7.5.2 definition only for the '**thread friction**'

```xml
<connection_0d>
   <loc> 84 60 10 </loc>
  <threaded_connection length="50" static_friction=”0.8” >                    <!-- head-to-washer -->
     <normal_direction x="0" y="0" z="-10"/>
     <washer outer_diameter=”20” attached=”false” static_friction=”0.8” />    <!-- washer-to-1stPart -->
     <bolt>
        <nut diameter="16." static_friction=”0.8”>                              <!-- nut-to-washer -->
          <washer outer_diameter=”25” attached=”false” static_friction=”0.8” /> <!-- nut_washer-to-lastPart -->
           </nut>
       </bolt>

       <contact_list>       <!-- 7.5.2 DEFINITION -->
		<contact thread=”true” static_friction=”0.8” />   <!-- only for thread friction -->	 
       </contact_list>
  </threaded_connection>

    <!-- 5.3.2. DEFINITION -->
   <contact_list>
	<contact_list>
		<contact>
			<partner label="part A"/>
			<partner label="part B"/>
			<coefficients static_friction="0.8"/>
		</contact>
		<contact>
			<partner label="part B"/>
			<partner label="part C"/>
			<coefficients static_friction="0.8"/>
		</contact>
		<contact>
			<partner label="part C"/>
			<partner label="part D"/>
			<coefficients static_friction="0.8"/>
		</contact>
   </contact_list>

</connection_0d>
````

# Conclusion

* I will add the local contact definition (5.3.2) for `<connection_2d>` as well, because its useful.

* We should promote an example containing the standard definition (5.3.2), rather than the thread_connection definition (7.5.2).
* The definition of 7.5.2 should be faded or **removed** from the standard (v3.1?).
We should think of a better alternative for expressing bolt/screw specific contacts, like
**thread-to-nut** or even **nut-to-washer**, **nut-to-last-part**, **head-to-washer**, etc.

**Comment by DrCaFr** [comment] 2019-05-12 21:45
A long text with plenty of questions ... I try to summarize:

1. "Table 136 (nested elements of connection_2d) does not have `<contact_list>`"
and
"I will add the local contact definition (5.3.2) for `<connection_2d>` as well, because its useful."
_--> confirmed._

2. "Section 7.5.2 has a competing local contact definition"
_--> Of course we need to fix contradictionary definitions! 
Unfortunately, I cannot remember how these came in place.
Sec. 5.3.2 definition has the disadvantage to allow contact between parts which are separated by other parts. Sec. 7.5.2 definition counts real gaps between adjacent sheets - but then needs to cope with frictions ad the head, the nut & washer and especially inside the thread.  
Hence, I would suggest moving the sec. 7.5.3 definition to sec. 5.3.2, replacing its current definition with element `<partner/>` - this for the general contact. The "threaded-specific" addition should stay in sec. 7.5.3, though.  
You say: "it is fragile: If order of connected parts change, the wrong friction will be assigned!".
This argument is valid.  
I suggest discussing this with Dr. Zhang <ins>before</ins> the AK meeting. Two examples, one for each variant, describing the same bolted connection incl. thread friction, would certainly foster this discussion.  
@economidis-nick : Would you please be so kind to provide these examples?  
(My thoughts address the 2nd and 3rd bullet point of your "Conclusion", too.)_

3. "we cannot fill the document with examples. Should we add references to the examples folder in GitHub?"
_--> I follow your argument._

**Comment by economidis-nick** [comment] 2019-10-07 16:15
According to pg.9 of the Darmstadt May 2019 meeting minutes,
we agreed to fade out the competing definition of section 7.5.3 and promote the one of section 5.3.2.
![image](https://user-images.githubusercontent.com/33229181/66329075-8c212900-e936-11e9-9f10-32cc49c6328d.png)

**Comment by economidis-nick** [comment] 2019-10-09 21:54
@DrCaFr , please review the text & example changes in section 7.5.2
If you are fine with it, I'll update the schema, examples and tests accordingly.

**Comment by DrCaFr** [comment] 2019-12-10 21:26
Question @economidis-nick: Is there any correlation assumed between the numbering of the &lt;level/>s and the direction of the screw / laser beam?  
I guess: No.  
Hence, I suggest to mention this as a remark somewhere.

**Comment by DrCaFr** [comment] 2019-12-10 21:37
Section "5.3.1.3 Special Topological situations" reviewed.
Minor modifications applied.
Please merge commit 90502b935343e1f595c4d0a1a8cf7b1452450a75 from "review_CF" into master branch!

**Comment by DrCaFr** [comment] 2019-12-10 23:42
The tables "Table 14: Nested elements of element &lt;contact_list/> " and "Table 48: Nested elements of element &lt;contact_list/>" appear to be duplicates and hence redundant. One of both should be removed.

**Comment by DrCaFr** [comment] 2019-12-10 23:46
Sections "5.3.2.2	Element &lt;contact/>" and "5.3.2.4	Element &lt;coefficients/>" on one side and "Table 49: Attributes of element &lt;contact/>" an the other are contradictory: The table states the friction coefficients to be attributes of &lt;contact/>, whereas section 5.3.2.4 defines a separate element for them.  
Please fix this!

**Comment by DrCaFr** [comment] 2019-12-10 23:49
Review finished with findings. Re-assigning this issue to Nick.

**Comment by economidis-nick** [comment] 2019-12-19 17:26
> The tables "Table 14: Nested elements of element <contact_list/> " and "Table 48: Nested elements of element <contact_list/>" appear to be duplicates and hence redundant. One of both should be removed.

`<connection_0d/contact_list>` and `<threaded_connection/contact_list>` are two separate and distinct definitions. That is why they appear to be duplicates.

The sole (remaining) purpose of `<threaded_connection/contact_list>` element is to denote the friction on the thread.
For this reason, in 9th Dec 2019 Meeting in Cologne, we agreed to remove the 
`<threaded_connection/contact_list>`  element altogether, and just add a `thread_static_friction` attribute to the `<threaded_connection>` element instead.

**Comment by economidis-nick** [comment] 2019-12-19 20:00
<contact_list> has been removed from 7.5.2 (Contacts and Friction) of Threaded Connections.
Its only remaining purpose, after simplification for issue #27, was to define the thread's friction coefficients.
 
The concept of 'thread friction coefficient' was is now expressed
as an attribute of <threaded_connection>:
- thread_static_friction
- thread_kinetic_friction

@DrCaFr please review the changes in : dd91838ce5bcf54d0681490eb93d32c8fefae839 
and if you agree, I will update the examples and schema, also.

**Comment by DrCaFr** [comment] 2020-03-09 12:28
See my commit ac90173bb8e04b73fdfdd3c669b14829a1b05e31. 
Review passed successful.

**Closed by DrCaFr** 2020-03-09 12:28 UTC
Labels: review
